# Generated by Django 4.2 on 2023-04-24 08:59

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('synopsis', models.TextField()),
                ('release_date', models.DateField()),
                ('country', models.CharField(choices=[('US', 'United States'), ('EN', 'England'), ('PL', 'Poland'), ('CA', 'Canada')], max_length=2)),
                ('poster', models.ImageField(upload_to='cookie/images/movies/')),
                ('genres', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='genres')),
            ],
        ),
    ]
