# Generated by Django 4.2 on 2023-04-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(choices=[('US', 'United States'), ('UK', 'United Kingdom'), ('PL', 'Poland'), ('CA', 'Canada')], max_length=2),
        ),
    ]
