# Generated by Django 4.2 on 2023-04-24 09:47

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('movies', '0002_alter_movie_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of genres.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='genres'),
        ),
    ]
