# Generated by Django 4.2 on 2023-04-25 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='author',
            new_name='rated_by',
        ),
    ]
