# Generated by Django 4.2.1 on 2023-05-23 11:27

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_rename_review_content_review_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='cookie/images/movies/', validators=[movies.models.validate_image]),
        ),
    ]
